"""Create devil fruit table

Revision ID: 4e51cc7af9aa
Revises: a21bad468b4c
Create Date: 2025-09-15 17:33:36.183389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e51cc7af9aa'
down_revision: Union[str, Sequence[str], None] = 'a21bad468b4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devil_fruits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('actual_user', sa.String(), nullable=True),
    sa.Column('type', sa.Enum('ZOAN', 'PARAMECIA', 'LOGIA', name='typeenumschema'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('devil_fruits')
    # ### end Alembic commands ###
