"""add update_at column to users table

Revision ID: a21bad468b4c
Revises: 701c00f92120
Create Date: 2025-08-20 18:39:41.271691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a21bad468b4c'
down_revision: Union[str, Sequence[str], None] = '701c00f92120'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table('users', schema=None) as batch_update_op:
    # ### commands auto generated by Alembic - please adjust! ###
        batch_update_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table('users', schema=None) as batch_update_op:
    # ### commands auto generated by Alembic - please adjust! ###
        batch_update_op.drop_column('updated_at')
    # ### end Alembic commands ###
